### ISSUE TITLE
大大 请教个问题 我要是想要加一个微信登录 微信支付 支付宝什么的 该怎么实现呢

### ISSUE THREAD

**Issue by lhz1208** [yujinjin/fans#1]
大大 请教个问题 我要是想要加一个微信登录 微信支付 支付宝什么的 该怎么实现呢

**Comment by yujinjin** [comment]
想加微信授权登录需要申请微信的appid、appsecret，manifest.json的SDK配置一下。具体地址是：http://ask.dcloud.net.cn/article/192
微信支付、支付宝支付参考教程：http://ask.dcloud.net.cn/article/71
