### ISSUE TITLE
请求app连接后台接口是如何操作的

### ISSUE THREAD

**Issue by bill1315** [yujinjin/fans#10]
关于app连接后台接口，是设置DEV.js的webapiDomain以及app.js中的isDebug=false吗，另外跨域访问是如何解决的？

**Comment by bill1315** [comment]
另外想问一下isApp这个参数有什么具体作用？

**Comment by yujinjin** [comment]
@bill1315  DEV.js是一个配置文件，它表示DEV环境下连接的配置。
关于跨域访问
纯H5是解决不了的，必须是后端服务配置请求头（Header）上设置Access-Control-Allow-Origin可跨域。
还有一种解决方案（只能在APP环境下）APP里专门做一层请求中转，客户端请求先到app，然后app再发请求到服务端。

关于isApp这个参数是因为H5的项目不仅仅会成为一个M站也会直接在APP里使用，在app环境和非app环境下的会有很多业务的需求是不同的甚至数据都不一样。

**Comment by bill1315** [comment]
@yujinjin ,谢谢解答，APP里专门做一层请求中转是如何操作的，另外我后端是java环境，可能设置的有问题，报“Cross-Origin Resource Sharing (CORS) Filter: Unsupported HTTP request header”，我再检查一下。

**Comment by yujinjin** [comment]
@bill1315  本项目可以使用html5plus的解决方案，文档地址：http://www.html5plus.org/doc/zh_cn/xhr.html

**Comment by bill1315** [comment]
@yujinjin ,收到，谢谢！

**Comment by bill1315** [comment]
@yujinjin ，已解决此问题，和前端没有关系，主要是后端要设置cors，spring 4.2以上提供注解功能，可惜设置无效，可能哪里配置出问题了，调试得不到配置spring配置里的参数，最终通过registry.addMapping全局设置搞定。谢谢。
