### ISSUE TITLE
楼主这个技术选项，还是蛮复杂的，请您的公司：要买车，是否使用这个开发了app？

### ISSUE THREAD

**Issue by wwb568109135** [yujinjin/fans#2]
（1）
楼主这个技术选项，还是蛮复杂的，请您的公司：要买车，是否使用这个开发了app？

（2）晚上找到了一个vue-cli的demo，还没尝试
https://github.com/4013465w/vue-template-for-hbuilder
相比您这个项目的技术选项，您的这个技术栈 其实还是蛮复杂的。

本人已有很熟练的开发vue2项目的经验，无奈手下的技术还需要在锻炼和培养中。。。
您的这个技术栈 其实还是蛮复杂的。
最后感谢楼主的这个项目 很不错，点赞

**Comment by yujinjin** [comment]
@wwb568109135 这个项目好像没有要买车公司的有关信息呀。你怎么知道的？
