### ISSUE TITLE
mac 上 npm run MR_DEV 报错，已经处理，且本地运行vuejs2成功

### ISSUE THREAD

**Issue by wwb568109135** [yujinjin/fans#3]
webpack 报错
![image](https://cloud.githubusercontent.com/assets/5113679/24186263/78082e88-0f12-11e7-89ae-073ddafe4d4f.png)

前台：
![image](https://cloud.githubusercontent.com/assets/5113679/24186306/aa3a602e-0f12-11e7-8c2c-f156fb3b0970.png)

**Comment by wwb568109135** [comment]
(1)图片1，已经解决
import config from './config/DEV'
（2）图片2，已经解决
import config from '../../config/DEV'


楼主应该考虑下，config这些配置，应该结合命令来用！

**Comment by yujinjin** [comment]
@wwb568109135 这个是各种环境的运行和打包配置。
我目前只配置了DEV环境以及相应的DEV运行、打包命令。
config已经是作为ProvidePlugin ，已经在webpack配置好了，可以直接引用不需要再额外引入。
![image](https://cloud.githubusercontent.com/assets/11609930/24196466/d8b81f2e-0f38-11e7-948a-6c804d07448e.png)

**Comment by wwb568109135** [comment]
@yujinjin 
NODE_ENV = process.env.NODE_ENV || "DEV", //环境类型
package.json 文件下的打包命令：

"MB_DEV": "export NODE_ENV=dev&export NODE_RUN=0&webpack --progress --hide-modules",

名称问题，文件大小写 有问题，我虽然不知道你执行的export NODE_ENV=dev  应该是导出NODE_ENV=dev，和webpack.config.js下面的NODE_ENV 判断有问题，大小写有问题！

**Comment by yujinjin** [comment]
@wwb568109135 现在最新的代码在MAC系统运行还有什么问题？
