### ISSUE TITLE
mac  下 打包发布dev文件  npm run MB_DEV

### ISSUE THREAD

**Issue by wwb568109135** [yujinjin/fans#4]
"MB_DEV": "export NODE_ENV=dev&set NODE_RUN=0&webpack --progress --hide-modules",

![image](https://cloud.githubusercontent.com/assets/5113679/24188287/bf2eab6c-0f1b-11e7-8157-d5ba6f10447b.png)

**Comment by yujinjin** [comment]
@wwb568109135  我用的是window系统，回头我在MAC上RUN一遍这些问题我一起修复掉

**Comment by yujinjin** [comment]
@wwb568109135 已修复
