### ISSUE TITLE
大大，最近我毕设打算做一个纯html5的安卓端app，有些问题想请教一下

### ISSUE THREAD

**Issue by MinuteWang** [yujinjin/fans#5]
我前端页面基本完成了（vue + webpack + vux + vue-router）,基本后台写写收发数据就可以了，我想问下是要经过两次打包生成apk吗？（先使用webpack进行打包生成最终文件，再使用apk打包工具对webpack生成的静态文件就行打包）
   这种静态文件在客户端的形式，需要对路由进行额外的操作吗？（因为我路由基本在前端设置，想用Ajax和后端通讯），但不知道打包后会不会出错。谢谢大大

**Comment by MinuteWang** [comment]
@yujinjin 
谢谢大大，能够理解
那么我开发一个完整的基于于web的应用（开发途中不用考虑如何打包的成安卓应用），最后通过HBuilder制作一个APP的壳，通过配置，打开就向服务器发出请求的方式获取应用信息也是可以的是吗？

**Comment by yujinjin** [comment]
@MinuteWang 
是可以的
