### ISSUE TITLE
转场动画空白的地方怎么去掉啊？还有感觉页面是刷新的

### ISSUE THREAD

**Issue by 7mus1c** [yujinjin/fans#7]
![qq 20170417113826](https://cloud.githubusercontent.com/assets/27657957/25078906/3a48a78c-236a-11e7-8b52-6777fc544624.png)
![qq 20170417113853](https://cloud.githubusercontent.com/assets/27657957/25078908/3e967a1c-236a-11e7-84a0-8e04bacd5e91.png)

**Comment by yujinjin** [comment]
@7mus1c 
转场的动画是左右切换，动画会让屏幕宽度增加一倍。
看起来像刷新的感觉是不是指的是底部导航栏，如果是这个问题原因是position的问题，我这2天会给修复掉。

**Comment by 7mus1c** [comment]
@yujinjin  
那这个动画会让屏幕宽度增加问题，我觉得会影响用户体验，这个问题希望能一并解决。谢谢了！
还有我是个初学者，能否加一下我的QQ：908160819，给个向你学习的机会！

**Comment by yujinjin** [comment]
@7mus1c  问题已修复。
其实这个转场的动画是为了让H5跟接近原生app，如果觉得的动画效果比较差可以自定义一套来实现。

**Comment by 7mus1c** [comment]
我现在还是一脸懵逼状态，webpack跟vue全家桶还没有配置好，已经好几天了。所以自己定义动画效果估计难做到！

**Comment by 7mus1c** [comment]
@

**Comment by yujinjin** [comment]
@7mus1c 你这里现在是什么问题？是这边git仓拉取的代码有问题吗？

**Comment by 7mus1c** [comment]
代码没有问题，就是webpack配置老出问题，好不容易配置好了，路由又出问题了，好麻烦的感觉。最好是能留个联系方式，遇到问题好请教你。

**Comment by 7mus1c** [comment]
我现在还是一脸懵逼状态，webpack跟vue全家桶还没有配置好，已经好几天了。所以自己定义动画效果估计难做到！

发自我的 iPhone

**Comment by yujinjin** [comment]
@7mus1c  好吧 我加你
